form/config/routes.rb
Rails.application.routes.draw do

  resources :experts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

form/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

form/app/models/expert.rb
class Expert < ApplicationRecord
  validates :name, presence: true
  validates :role, presence: true
  has_many :relationships
end

form/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :expert
end

form/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

form/app/controllers/experts_controller.rb
class ExpertsController < ApplicationController
  def index
    @experts = Expert.all
  end

  def show
    @expert = Expert.find(params[:id])
    @relationships = Relationship.where(follower_id: @expert.id)
  end

  def new
    @expert = Expert.new
  end

  #def edit
  #  @expert = Expert.find(params[:id])
  #end

  def create
    @expert = Expert.new(expert_params)
    #render plain: params[:expert].inspect
    if @expert.save
      redirect_to @expert
    else
      render 'new'
    end
  end

  private
    def expert_params
      params.require(:expert).permit(:name, :role, :linkedin, :researchgate, :bio)
    end
end

form/app/helpers/application_helper.rb
module ApplicationHelper
end

form/app/helpers/experts_helper.rb
module ExpertsHelper
end

form/app/views/experts/index.html.erb
<h1 style="text-align:center;"> Propel(x) Experts</h1>

<table align="center">
  <tr>
    <th>Expert</th>
    <th>Role</th>
    <th>LinkedIn</th>
    <th>ResearchGate</th>
    <th></th>
  </tr>

  <% @experts.each do |exp| %>
    <tr>
      <td><%= exp.name %></td>
      <td><%= exp.role %></td>
      <td><%= exp.linkedin %></td>
      <td><%= exp.researchgate %></td>
      <td><%= link_to 'More Info', expert_path(exp) %></td>
    </tr>
  <% end %>
</table>
<br>
<p style="text-align:center;">
  <%= link_to 'Sign Up!', new_expert_path %>
</p>

form/app/views/experts/new.html.erb
<h1>New Expert Profile</h1>

<%= form_with scope: :expert, url: experts_path, local: true do |f| %>

  <% if @expert.errors.any? %>
    <div id="errors">
      <h2>
        <%= pluralize(@expert.errors.count, 'field') %> invalid:
      </h2>
      <ul>
        <% @expert.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name, 'Full Name:' %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :role, 'Current Role:' %><br>
    <%= f.text_field :role %>
  </p>

  <p>
    Picture:<br>
    <%= f.file_field :picture %>
  </p>

  <p>
    <%= f.label :linkedin, 'LinkedIn Profile:' %><br>
    <%= f.text_field :linkedin %>
  </p>

  <p>
    <%= f.label :researchgate, 'ResearchGate Profile:' %><br>
    <%= f.text_field :researchgate %>
  </p>

  <p>
    <%= f.label :bio, 'Short Bio:' %><br>
    <%= f.text_area :bio %>
  </p>

  <p>
    <%= f.submit 'Submit!' %>
  </p>
<% end %>

<%= link_to 'All Experts', experts_path %>

form/app/views/experts/show.html.erb
<h1 align="center">
  <%= @expert.name %>
</h1>

<p align="center">
  <strong>Current Role:</strong>
  <%= @expert.role %>
</p>

<p align="center">
  <strong>Followers:</strong>
  <%= @relationships.count %>
</p>

<p align="center">
  <strong>Bio:</strong>
  <%= @expert.bio %>
</p>

<p align="center">
  <strong>LinkedIn Profile:</strong>
  <%= @expert.linkedin %>
</p>

<p align="center">
  <strong>ResearchGate:</strong>
  <%= @expert.researchgate %>
</p>

<p align="center">
  <%= link_to 'All Experts', experts_path %>
</p>

form/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Form</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>